// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXbQM5HL14rlUUEV175d9WMQGHSsBg5KY',
    appId: '1:302253235206:web:5db0716d4c167afc22f787',
    messagingSenderId: '302253235206',
    projectId: 'e-agribusiness-3c7b8',
    authDomain: 'e-agribusiness-3c7b8.firebaseapp.com',
    storageBucket: 'e-agribusiness-3c7b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBurFBemBuOVN3gnsHTwv8pQc23GN0PoD0',
    appId: '1:302253235206:android:3a231bf0784a40f922f787',
    messagingSenderId: '302253235206',
    projectId: 'e-agribusiness-3c7b8',
    storageBucket: 'e-agribusiness-3c7b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAunVgTc4Di0Xl4_SDO3KojsELWc3XeDXk',
    appId: '1:302253235206:ios:185c93284a2b3f6822f787',
    messagingSenderId: '302253235206',
    projectId: 'e-agribusiness-3c7b8',
    storageBucket: 'e-agribusiness-3c7b8.firebasestorage.app',
    iosClientId: '302253235206-qvtgl82smmdeg6btg6a67j2tbesabos2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eAgribusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAunVgTc4Di0Xl4_SDO3KojsELWc3XeDXk',
    appId: '1:302253235206:ios:185c93284a2b3f6822f787',
    messagingSenderId: '302253235206',
    projectId: 'e-agribusiness-3c7b8',
    storageBucket: 'e-agribusiness-3c7b8.firebasestorage.app',
    iosClientId: '302253235206-qvtgl82smmdeg6btg6a67j2tbesabos2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eAgribusiness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXbQM5HL14rlUUEV175d9WMQGHSsBg5KY',
    appId: '1:302253235206:web:9ca1a2fd0b36019222f787',
    messagingSenderId: '302253235206',
    projectId: 'e-agribusiness-3c7b8',
    authDomain: 'e-agribusiness-3c7b8.firebaseapp.com',
    storageBucket: 'e-agribusiness-3c7b8.firebasestorage.app',
  );

}